### PR TITLE
Add 'NewLine' to list of expected node types

### LINKED ISSUE #1: Unexpected node type NewLine at walkAST (index.js:46:13)
Example jade:

```
script.
    foo('bar')
    var a = b
```

Breaks as a result of the new line. Issues can be fixed by adding `case 'NewLine':` after https://github.com/jadejs/jade-walk/blob/master/index.js#L43, but would this break anything else, or allow anything invalid through?

### PR DESCRIPTION
**Pull request by benedfit**
Closes #1

### CODE REVIEW

**Comment by yangsu** [comment]
Ping @ForbesLindesay @hemanth @bloodyowl

**Comment by hemanth** [comment]
:+1:

**Comment by benedfit** [comment]
Thanks. Any chance of an `npm publish` too?

**Comment by hemanth** [comment]
@ForbesLindesay must do it.

**Pull request merged**
